<?php

declare(strict_types=1);

namespace Jengo\Base\Support;

class JengoDirectory
{
    /**
     * Get the absolute path to the .jengo directory or a subpath within it.
     */
    public static function path(?string $subpath = null): string
    {
        $root = defined('ROOTPATH') ? ROOTPATH : (getcwd() . DIRECTORY_SEPARATOR);
        $base = rtrim($root, '/\\') . DIRECTORY_SEPARATOR . '.jengo';

        if ($subpath === null || $subpath === '') {
            return $base;
        }

        return $base . DIRECTORY_SEPARATOR . ltrim($subpath, '/\\');
    }

    /**
     * Ensure that the .jengo directory (and optional subdirectories) exists and has a .gitignore.
     */
    public static function ensureExists(?string $subpath = null): string
    {
        $target = $subpath !== null ? self::path($subpath) : self::path();

        // If subpath is a file path (has extension), get its directory
        $dir = pathinfo($target, PATHINFO_EXTENSION) !== '' ? dirname($target) : $target;

        if (! is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        // Ensure root .jengo directory has a .gitignore
        $gitignore = self::path('.gitignore');
        if (! file_exists($gitignore) || file_get_contents($gitignore) === "cache/\n") {
            file_put_contents($gitignore, "*\n!.gitignore\n");
        }

        return $target;
    }

    /**
     * Determine if a file exists inside the .jengo directory.
     */
    public static function has(string $file): bool
    {
        return is_file(self::path($file));
    }

    /**
     * Get the raw contents of a file in .jengo.
     */
    public static function get(string $file): ?string
    {
        $path = self::path($file);

        if (! is_file($path)) {
            return null;
        }

        $contents = file_get_contents($path);

        return $contents !== false ? $contents : null;
    }

    /**
     * Write contents to a file inside .jengo atomically.
     */
    public static function put(string $file, string $contents): void
    {
        $target = self::ensureExists($file);
        $temp = $target . '.' . uniqid('tmp_', true);

        file_put_contents($temp, $contents, LOCK_EX);
        rename($temp, $target);
    }

    /**
     * Write an array to an exportable PHP return file for opcache acceleration.
     *
     * @param array<string, mixed> $data
     */
    public static function writePhpArray(string $file, array $data): void
    {
        $exported = var_export($data, true);
        $code = "<?php\n\ndeclare(strict_types=1);\n\n// Auto-generated by Jengo. Do not edit directly.\nreturn {$exported};\n";

        self::put($file, $code);
    }

    /**
     * Read an exported PHP array file from .jengo.
     *
     * @param array<string, mixed> $default
     * @return array<string, mixed>
     */
    public static function readPhpArray(string $file, array $default = []): array
    {
        $path = self::path($file);

        if (! is_file($path)) {
            return $default;
        }

        try {
            $data = require $path;
            return is_array($data) ? $data : $default;
        } catch (\Throwable) {
            return $default;
        }
    }

    /**
     * Write JSON data into .jengo.
     */
    public static function writeJson(string $file, mixed $data, int $flags = JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES): void
    {
        $json = json_encode($data, $flags);
        self::put($file, $json !== false ? $json : '{}');
    }

    /**
     * Read JSON data from .jengo.
     */
    public static function readJson(string $file, mixed $default = null): mixed
    {
        $raw = self::get($file);

        if ($raw === null) {
            return $default;
        }

        try {
            return json_decode($raw, true, 512, JSON_THROW_ON_ERROR);
        } catch (\Throwable) {
            return $default;
        }
    }

    /**
     * Delete a file inside .jengo.
     */
    public static function delete(string $file): bool
    {
        $path = self::path($file);

        if (is_file($path)) {
            return unlink($path);
        }

        return false;
    }

    /**
     * Flush all files inside .jengo (preserving .gitignore).
     */
    public static function flush(): void
    {
        $base = self::path();

        if (! is_dir($base)) {
            return;
        }

        $items = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($base, \RecursiveDirectoryIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::CHILD_FIRST
        );

        foreach ($items as $item) {
            if ($item->getFilename() === '.gitignore') {
                continue;
            }

            if ($item->isDir()) {
                @rmdir($item->getRealPath());
            } else {
                @unlink($item->getRealPath());
            }
        }
    }
}
